export enum ActionType {
    GET_PARAMETERS = "GET_PARAMETERS",
    GET_ID_PARAMETER = "GET_ID_PARAMETER",
    CREATE_PARAMETER = "CREATE_PARAMETER",
    DELETE_PARAMETERS = "DELETE_PARAMETERS",
    PUT_PARAMETERS = "PUT_PARAMETERS",
}